name: Scan GitHub notifications
on:
  schedule:
    - cron: "*/5 * * * *" # Every 5 minutes
  workflow_dispatch:
jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    container: openruntimes/node:17.0
    steps:
      - name: Main
        run: |
          apk add curl
          sh /usr/local/src/start.sh &
          sleep 10
          curl -H "X-Internal-Challenge: ${INTERNAL_RUNTIME_KEY}" -H "Content-Type: application/json" -X POST http://localhost:3000/ -d '{"payload": "{}"}'
        env:
          INTERNAL_RUNTIME_KEY: ${{ secrets.INTERNAL_RUNTIME_KEY }}
          GITHUB_WEBHOOK: ${{ secrets.DB_DATABASE }}
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          DISCORD_PING_USER: ${{ secrets.DISCORD_PING_USER }}