name: Scan GitHub notifications
on:
  schedule:
    - cron: "*/5 * * * *" # Every 5 minutes
  workflow_dispatch:
jobs:
  scan-and-notify:
    name: Scan and Notify
    runs-on: ubuntu-latest
    container: openruntimes/node:17.0
    steps:
      - name: Start OPR
        run: |
          ls
          pwd
          apk add curl
          cp code.tar.gz /tmp/code.tar.gz
          sh /usr/local/src/start.sh &
        env:
          INTERNAL_RUNTIME_KEY: ${{ secrets.INTERNAL_RUNTIME_KEY }}
      - name: Execute OPR
        run: |
          sleep 5
          curl -H "X-Internal-Challenge: ${INTERNAL_RUNTIME_KEY}" -H "Content-Type: application/json" -X POST http://localhost:3000/ -d '{"payload": "{}"}'
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          DISCORD_PING_USER: ${{ secrets.DISCORD_PING_USER }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
